logging:
  register-shutdown-hook: true
  level:
    web: debug
    org.springframework.web: debug
    com.platform.gateway.*: debug

server:
  port: 9000
  shutdown: graceful

spring:
  application.name: platform-gateway
  cloud.nacos.config:
    server-addr: 127.0.0.1:8848
    file-extension: yaml
  config.import: nacos:platform-gateway.yaml

springdoc.swagger-ui.path: /swagger-ui