logging:
  register-shutdown-hook: true
  level:
    web: debug
    org.springframework.web: debug
    com.platform.system.*: debug
    org.springframework.r2dbc: debug
    io.r2dbc.postgresql:
      #QUERY: debug
      PARAM: debug
      #client: debug
server:
  port: 0
  shutdown: graceful

spring:
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
    - org.springframework.boot.autoconfigure.security.reactive.ReactiveUserDetailsServiceAutoConfiguration
  application.name: platform-system
  cloud.nacos.config:
    server-addr: 127.0.0.1:8848
    file-extension: yaml
  config.import: nacos:platform-system.yaml
  r2dbc:
    url: r2dbc:postgres://127.0.0.1:5432/country
    username: farmer
    password: q1w2e3..
  sql.init.mode: never

springdoc.swagger-ui.path: /swagger-ui